services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
      - POSTGRES_DB=${POSTGRES_DB:-mydatabase}
    ports:
      - '${POSTGRES_PORT:-51214}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_js_test_network

volumes:
  postgres_data:

networks:
  nest_js_test_network:
