// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import dotenv from 'dotenv';
import dotenvExpand from 'dotenv-expand';
import { defineConfig, env } from 'prisma/config';

dotenvExpand.expand(dotenv.config()); // для корректной работы переменных окружения с вложенными ссылками,
// например, DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public

// Альтернативный (кастомный) вариант, который был раньше.
// Оставляю как быстрый backup-вариант, если захотите уйти от dotenv-expand.
// Как включить:
// 1) Раскомментируйте функцию ниже.
// 2) Замените в datasource `url: env('DATABASE_URL')` на:
//    `url: expandEnvTemplate(process.env['DATABASE_URL'])`
// function expandEnvTemplate(value: string | undefined): string | undefined {
//   if (!value) {
//     return value;
//   }
//
//   return value.replace(/\$\{([A-Z0-9_]+)\}/gi, (_, variableName: string) => {
//     return process.env[variableName] ?? '';
//   });
// }

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'), // адрес подключения к базе данных PostgreSQL из .env
  },
});
